version: '2'
services:
    sampletest-app:
        image: sampletest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sampletest-mysql:3306/sampletest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sampletest-mysql:
        extends:
            file: mysql.yml
            service: sampletest-mysql
